In [2]:
import pandas as pd

In [3]:
df = pd.read_csv(
    "../data/raw/motor_insurance.csv",
    sep=";"
)

df.head()

,insured_id,year,policy_type,policy_status,business_type,payment_frequency,bonus_score,driver_age,vehicle_age,age_driving_licence,...,liability_property_incurred,liability_injury_incurred,property_incurred,theft_incurred,fire_incurred,glass_incurred,legal_protection_incurred,occupants_incurred,total_exposure,liability_exposure
0,1,2022,COMP_E,C,NB,A,G,48,22.0,26.0,...,0.000,0.0,0.0000,0.0,0.0,0.0,0.0,0.0,0.09863,0.09863
1,2,2022,COMP_E,A,P,A,G,43,24.0,19.0,...,0.000,0.0,0.0000,0.0,0.0,0.0,0.0,0.0,1.00000,1.00000
2,2,2023,COMP_E,A,P,A,G,44,25.0,19.0,...,233.013,0.0,0.0000,0.0,0.0,0.0,0.0,0.0,1.00000,1.00000
3,2,2024,COMP_E,A,P,A,G,45,26.0,18.0,...,1035.000,0.0,1551.3615,0.0,0.0,0.0,0.0,0.0,1.00000,1.00000
4,3,2022,COMP_E,A,NB,S,G,45,26.0,19.0,...,0.000,0.0,0.0000,0.0,0.0,0.0,0.0,0.0,1.00000,1.00000

In [8]:
info_df = pd.DataFrame({
    "Column": df.columns,
    "Data Type": df.dtypes.astype(str),
    "Non-Null Count": df.count().values,
    "Missing Values": df.isnull().sum().values
})

info_df

,Column,Data Type,Non-Null Count,Missing Values
insured_id,insured_id,int64,354140,0
year,year,int64,354140,0
policy_type,policy_type,str,354140,0
policy_status,policy_status,str,354140,0
business_type,business_type,str,354140,0
payment_frequency,payment_frequency,str,354140,0
bonus_score,bonus_score,str,354140,0
driver_age,driver_age,int64,354140,0
vehicle_age,vehicle_age,float64,354138,2
age_driving_licence,age_driving_licence,float64,354138,2
fuel_type,fuel_type,str,352853,1287
vehicle_value,vehicle_value,float64,353627,513
seats,seats,int64,354140,0
power_to_weight_ratio,power_to_weight_ratio,float64,354140,0
vehicle_brand,vehicle_brand,str,354140,0
municipality_type,municipality_type,str,354140,0
circulation_area,circulation_area,str,354140,0
total_premium,total_premium,float64,354140,0
liability_premium,liability_premium,float64,354140,0
property_damage_premium,property_damage_premium,float64,354140,0
theft_premium,theft_premium,float64,354140,0
fire_premium,fire_premium,float64,354140,0
glass_premium,glass_premium,float64,354140,0
legal_protection_premium,legal_protection_premium,float64,354140,0
occupants_premium,occupants_premium,float64,354140,0
total_claims,total_claims,int64,354140,0
liability_claims,liability_claims,int64,354140,0
liability_property_claims,liability_property_claims,int64,354140,0
liability_injury_claims,liability_injury_claims,int64,354140,0
property_claims,property_claims,int64,354140,0
theft_claims,theft_claims,int64,354140,0
fire_claims,fire_claims,int64,354140,0
glass_claims,glass_claims,int64,354140,0
legal_protection_claims,legal_protection_claims,int64,354140,0
occupants_claims,occupants_claims,int64,354140,0
total_incurred,total_incurred,float64,354140,0
liability_incurred,liability_incurred,float64,354140,0
liability_property_incurred,liability_property_incurred,float64,354140,0
liability_injury_incurred,liability_injury_incurred,float64,354140,0
property_incurred,property_incurred,float64,354140,0
theft_incurred,theft_incurred,float64,354140,0
fire_incurred,fire_incurred,float64,354140,0
glass_incurred,glass_incurred,float64,354140,0
legal_protection_incurred,legal_protection_incurred,float64,354140,0
occupants_incurred,occupants_incurred,float64,354140,0
total_exposure,total_exposure,float64,354140,0
liability_exposure,liability_exposure,float64,354140,0

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 354140 entries, 0 to 354139
Data columns (total 47 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   insured_id                   354140 non-null  int64
 1   year                         354140 non-null  int64
 2   policy_type                  354140 non-null  str
 3   policy_status                354140 non-null  str
 4   business_type                354140 non-null  str
 5   payment_frequency            354140 non-null  str
 6   bonus_score                  354140 non-null  str
 7   driver_age                   354140 non-null  int64
 8   vehicle_age                  354138 non-null  float64
 9   age_driving_licence          354138 non-null  float64
 10  fuel_type                    352853 non-null  str
 11  vehicle_value                353627 non-null  float64
 12  seats                        354140 non-null  int64
 13  power_to_weight_ratio        354140 non-null  float64
 14  vehicle_brand                354140 non-null  str
 15  municipality_type            354140 non-null  str
 16  circulation_area             354140 non-null  str
 17  total_premium                354140 non-null  float64
 18  liability_premium            354140 non-null  float64
 19  property_damage_premium      354140 non-null  float64
 20  theft_premium                354140 non-null  float64
 21  fire_premium                 354140 non-null  float64
 22  glass_premium                354140 non-null  float64
 23  legal_protection_premium     354140 non-null  float64
 24  occupants_premium            354140 non-null  float64
 25  total_claims                 354140 non-null  int64
 26  liability_claims             354140 non-null  int64
 27  liability_property_claims    354140 non-null  int64
 28  liability_injury_claims      354140 non-null  int64
 29  property_claims              354140 non-null  int64
 30  theft_claims                 354140 non-null  int64
 31  fire_claims                  354140 non-null  int64
 32  glass_claims                 354140 non-null  int64
 33  legal_protection_claims      354140 non-null  int64
 34  occupants_claims             354140 non-null  int64
 35  total_incurred               354140 non-null  float64
 36  liability_incurred           354140 non-null  float64
 37  liability_property_incurred  354140 non-null  float64
 38  liability_injury_incurred    354140 non-null  float64
 39  property_incurred            354140 non-null  float64
 40  theft_incurred               354140 non-null  float64
 41  fire_incurred                354140 non-null  float64
 42  glass_incurred               354140 non-null  float64
 43  legal_protection_incurred    354140 non-null  float64
 44  occupants_incurred           354140 non-null  float64
 45  total_exposure               354140 non-null  float64
 46  liability_exposure           354140 non-null  float64
dtypes: float64(24), int64(14), str(9)
memory usage: 127.0 MB

## Initial Observations

- Policy data spans 2022-2024
- Dataset contains 354140 policy records
- Contains 47 variables
- Most columns do not have missing values
- fuel_type and vehicle_value contain some missing values